controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
homepage:
    path: /homepage
    controller: App\Controller\HomePageController::home
products:
    path: /products
    controller: App\Controller\ProductsController::getProducts
contact:
    path: /contact
    controller: App\Controller\ContactController::contact